# Generated by Django 4.1.4 on 2022-12-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='assignement',
        ),
        migrations.AddField(
            model_name='milestone',
            name='assignement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
