# Generated by Django 4.1.4 on 2022-12-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_remove_module_assignement_milestone_assignement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course_app.course'),
        ),
    ]
