# Generated by Django 4.1.4 on 2022-12-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_rename_courses_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
