# Generated by Django 4.1.4 on 2022-12-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_alter_milestone_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='course',
        ),
    ]
