# Generated by Django 4.1.4 on 2022-12-10 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_app.course'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Milestone Name'),
        ),
    ]
