# Generated by Django 4.1.4 on 2022-12-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_milestone_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Module',
            new_name='module',
        ),
    ]
