# Generated by Django 4.1.4 on 2022-12-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_course_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=150)),
                ('facebook', models.URLField()),
                ('image', models.URLField(max_length=250)),
            ],
        ),
    ]
