# Generated by Django 4.1.4 on 2022-12-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_modules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
    ]
