# Generated by Django 4.1.4 on 2022-12-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_rename_modules_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='youtube',
        ),
    ]
