# Generated by Django 4.1.4 on 2022-12-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_remove_module_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='assignement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Module Name')),
                ('yotube_link', models.CharField(max_length=100, verbose_name='Youtube Video')),
                ('Module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_app.module')),
            ],
        ),
    ]
