# Generated by Django 4.1.4 on 2022-12-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0011_video_created_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Video Title'),
        ),
    ]
